<?php
return [
	[
		'campaignname' => 'Campaign 1',
		'advertiser' => 'Advertiser A',
		'code' => 'AD001',
		'creative_type' => 'image',
		'image_url' => 'https://example.com/campaign1-banner.jpg',
		'url' => 'https://example.com/landing1',
		'price' => 3.5,
		'creative_id' => 'CR001',
		'hs_os' => 'ios,android',
		'country' => 'us',
		'dimension' => '300x250',
		'appid' => null, // Added from third array
		'tld' => null, // Added from third array
		'portalname' => null, // Added from third array
		'day_capping' => null, // Added from third array
		'attribute' => null, // Added from third array
		'billing_id' => null, // Added from third array
		'bidtype' => null, // Added from third array
		'htmltag' => null, // Added from third array
		'from_hour' => null, // Added from third array
		'to_hour' => null, // Added from third array
		'operator' => null, // Added from third array
		'device_make' => null, // Added from third array
		'city' => null, // Added from third array
		'lat' => null, // Added from third array
		'lng' => null, // Added from third array
		'app_name' => null, // Added from third array
		'user_list_id' => null, // Added from third array
		'adplay_logo' => null, // Added from third array
		'vast_video_duration' => null, // Added from third array
		'logo_placement' => null, // Added from third array
		'hs_model' => null, // Added from third array
		'is_rewarded_inventory' => null, // Added from third array
		'pixel_tag' => null, // Added from third array
		'dmp_campaign_audience' => null, // Added from third array
		'platform' => null, // Added from third array
		'open_publisher' => null, // Added from third array
		'audience_targeting' => null, // Added from third array
		'native_title' => null, // Added from third array
		'native_type' => null, // Added from third array
		'native_data_value' => null, // Added from third array
		'native_data_cta' => null, // Added from third array
		'native_data_rating' => null, // Added from third array
		'native_data_price' => null, // Added from third array
		'native_img_icon' => null // Added from third array
	],
	[
		'campaignname' => 'Campaign 2',
		'advertiser' => 'Advertiser B',
		'creative_type' => 'video',
		'image_url' => 'https://example.com/campaign2-banner.jpg',
		'url' => 'https://example.com/landing2',
		'price' => 4.0,
		'code' => 'AD002',
		'creative_id' => 'CR002',
		'hs_os' => 'android',
		'country' => 'us',
		'dimension' => '728x90',
		'appid' => null, // Added from third array
		'tld' => null, // Added from third array
		'portalname' => null, // Added from third array
		'day_capping' => null, // Added from third array
		'attribute' => null, // Added from third array
		'billing_id' => null, // Added from third array
		'bidtype' => null, // Added from third array
		'htmltag' => null, // Added from third array
		'from_hour' => null, // Added from third array
		'to_hour' => null, // Added from third array
		'operator' => null, // Added from third array
		'device_make' => null, // Added from third array
		'city' => null, // Added from third array
		'lat' => null, // Added from third array
		'lng' => null, // Added from third array
		'app_name' => null, // Added from third array
		'user_list_id' => null, // Added from third array
		'adplay_logo' => null, // Added from third array
		'vast_video_duration' => null, // Added from third array
		'logo_placement' => null, // Added from third array
		'hs_model' => null, // Added from third array
		'is_rewarded_inventory' => null, // Added from third array
		'pixel_tag' => null, // Added from third array
		'dmp_campaign_audience' => null, // Added from third array
		'platform' => null, // Added from third array
		'open_publisher' => null, // Added from third array
		'audience_targeting' => null, // Added from third array
		'native_title' => null, // Added from third array
		'native_type' => null, // Added from third array
		'native_data_value' => null, // Added from third array
		'native_data_cta' => null, // Added from third array
		'native_data_rating' => null, // Added from third array
		'native_data_price' => null, // Added from third array
		'native_img_icon' => null // Added from third array
	],
	[
		"campaignname" => "Test_Banner_13th-31st_march_Developer",
		"advertiser" => "TestGP",
		"code" => "118965F12BE33FB7E",
		"appid" => "20240313103027",
		"tld" => "https://adplaytechnology.com/",
		"portalname" => null,
		"creative_type" => "1",
		"creative_id" => 167629,
		"day_capping" => 0,
		"dimension" => "320x480",
		"attribute" => "rich-media",
		"url" => "https://adplaytechnology.com/",
		"billing_id" => "123456789",
		"price" => 0.1,
		"bidtype" => "CPM",
		"image_url" => "https://s3-ap-southeast-1.amazonaws.com/elasticbeanstalk-ap-southeast-1-5410920200615/CampaignFile/20240117030213/D300x250/e63324c6f222208f1dc66d3e2daaaf06.png",
		"htmltag" => null,
		"from_hour" => "0",
		"to_hour" => "23",
		"hs_os" => "Android,iOS,Desktop",
		"operator" => "Banglalink,GrameenPhone,Robi,Teletalk,Airtel,Wi-Fi",
		"device_make" => "No Filter",
		"country" => "Bangladesh",
		"city" => null,
		"lat" => null,
		"lng" => null,
		"app_name" => null,
		"user_list_id" => 0,
		"adplay_logo" => 1,
		"vast_video_duration" => null,
		"logo_placement" => 1,
		"hs_model" => null,
		"is_rewarded_inventory" => 0,
		"pixel_tag" => null,
		"dmp_campaign_audience" => 0,
		"platform" => null,
		"open_publisher" => 1,
		"audience_targeting" => 0,
		"native_title" => null,
		"native_type" => null,
		"native_data_value" => null,
		"native_data_cta" => null,
		"native_data_rating" => null,
		"native_data_price" => null,
		"native_img_icon" => null
	]
];
